apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart.serviceAccountName" .  }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    {{- include "chart.annotations" . | nindent 4 }}